print("Entrer le nom du chat 1 : ")
chat_1 =input()
print("Entrer le nom du chat 2 : ")
chat_2 = input()
print("Entrer le nom du chat 3 : ")
chat_3 = input()
print("Entrer le nom du chat 4 : ")
chat_4 = input()
print(f"{chat_1} {chat_2} {chat_3} {chat_4}")
